dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam

addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - gcc-multilib

env:
  global:
  - NJOBS=2
  - COMPILER="4.06.1"
  - CAMLP5_VER="7.05"
  - FINDLIB_VER="1.8.0"
  - NATIVE_COMP="yes"
  - COQ_VER="dev"

install:
- opam init -j ${NJOBS} -n -y
- opam update
- opam switch set ${COMPILER}
- eval $(opam config env)
- opam config list
- opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev || echo "coq-core-dev registered"
- opam install -j ${NJOBS} -y camlp5.${CAMLP5_VER} ocamlfind.${FINDLIB_VER} coq.${COQ_VER}
- opam upgrade -y coq.${COQ_VER}
- opam list

script:
 - make -j ${NJOBS} VERBOSE=1 all test-suite

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1d832177d55504ef1fba
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
