(* Distributed under the terms of the MIT license.   *)

From Template Require Export
     utils        (* Utility functions *)
     config       (* Configurations *)
     monad_utils  (* Monadic notations *)
     Ast          (* The term AST *)
     AstUtils     (* Utilities on the AST *)
     Loader       (* Declaration of the Template Coq plugin *)
     Induction    (* Induction *)
     LiftSubst    (* Lifting and substitution for terms *)
     WeakSubst    (* Weakening and substitution lemmas *)
     UnivSubst    (* Substitution of universe instances *)
     Typing       (* Typing judgment *)
     Checker.     (* Partial typechecker implementation *)