name: Test compilation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        coq_version: 
          - 'dev'
        ocaml_version:
          - '4.07-flambda'
        target: [ local, opam ]
      fail-fast: true

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Docker-Coq-Action
        uses: coq-community/docker-coq-action@v1
        with:
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          before_script: |
            startGroup "Workaround permission issue"
              sudo chown -R coq:coq .  # <--
              opam exec -- ocamlfind list
            endGroup
          script: |
            startGroup "Build project"
              opam exec -- ./configure.sh --enable-${{matrix.target}}
              opam exec -- make -j 2 ci-${{matrix.target}}
            endGroup
          uninstall: |
            startGroup "Clean project"
            endGroup

      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .  # <--
